@localhost=localhost:4004/odata/v4/main
@id=a2d5f7c9-6b14-4e3a-9c2f-8d1b7e5a0c66


GET  http://{{localhost}}/Customers
Content-Type: application/json


###
POST http://{{localhost}}/Customers
Content-Type: application/json

{
   "id" : "{{id}}",
   "firstName" : "Jailson",
   "lastName" : "Ribeiro",
   "email" : "jailson.ribeiro@example.com"
}


###
DELETE http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json


###

PATCH  http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

{
   "firstName" : "Luiz2"
}


###
GET  http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json