@localhost=localhost:4004/odata/v4/main
@id=4e8a1c2d-9f73-4b6e-a5d1-3c7f8b2e0a91
@customer_id=a2d5f7c9-6b14-4e3a-9c2f-8d1b7e5a0c66

@product_id=d9c3b6a1-2f8e-4d7b-9a5c-1e7f0b2a4d88


GET  http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json


###
PUT    http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

 {
 "id": "{{id}}",
 "customer_id": "{{customer_id}}",
 "totalAmount": 19.30 ,
 "items": [
    {
        "id": "c1a7f9d4-3e2b-4f6a-8c91-2d7e5b0a9f13",
        "header_id": "{{id}}",
        "product_id": "{{product_id}}",
        "quantity": 750,
        "price": 1000.00 
    },
    {
        "id": "7b9e2c6a-1f4d-4a88-b3e7-6c2f9d1a5e44",
        "header_id": "{{id}}",
        "product_id": "{{product_id}}",
        "quantity": 100,
        "price": 2000 
    }
  ]
 }

###
DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###
PATCH  http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

{
   "totalAmount": 250.99
}


###
GET  http://{{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items 
Content-Type: application/json

###
GET  http://{{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=customer,items($filter=quantity gt 150;$expand=product)
Content-Type: application/json


###
GET  http://{{localhost}}/SalesOrderHeaders?&$expand=customer,items($filter=price gt 100;$expand=product)
Content-Type: application/json


###
GET  http://{{localhost}}/SalesOrderHeaders?$select=id,totalAmount,createdBy&$filter=createdBy eq 'Luiz@example.com'&$expand=items
Content-Type: application/json